[platformio]
default_envs = nano33ble

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D SENSOR_POINT=chest
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Select the environment that matches the IMU on the physical board.
[env:nano33ble]
lib_deps =
    arduino-libraries/Arduino_LSM9DS1
    arduino-libraries/ArduinoBLE

[env:nano33ble_rev2]
build_flags =
    ${env.build_flags}
    -D IMU_REV2
lib_deps =
    arduino-libraries/Arduino_BMI270_BMM150
    arduino-libraries/ArduinoBLE
