[env]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200

; Select the environment that matches the IMU on the physical board.
[env:nano33ble]
lib_deps =
    arduino-libraries/Arduino_LSM9DS1
    arduino-libraries/ArduinoBLE

[env:nano33ble_rev2]
lib_deps =
    arduino-libraries/Arduino_BMI270_BMM150
    arduino-libraries/ArduinoBLE
